service: alchemist

provider:
  name: aws
  runtime: nodejs4.3
  stage: prod
  region: us-east-1
  profile: alchemist
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "*"

package:
  artifact: dst.zip

functions:
  metamorphose:
    handler: handlers.metamorphose
    events:
      - http:
          path: metamorphose
          method: get
      - http:
          path: metamorphose/{proxy+}
          method: get
